### ISSUE TITLE
issue with version 2.5.9.2 - OK with 2.5.11.0

### ISSUE THREAD

**Issue by chris05** [stephanmahieu/formhistorycontrol-2#183]
**Describe the bug**
indefinitely loaded, invalid date with last version 2.5.9.2

**To Reproduce**
on each site visited

**Expected behavior**
displaying the history of entries

**Screenshots**
![Image](https://github.com/user-attachments/assets/66f6cc9a-8e52-45b4-8414-10ddbeee54ca)
![Image](https://github.com/user-attachments/assets/59c35a28-752f-451a-bb46-d0a7a8c1cd07)

**Desktop (please complete the following information):**
 - OS: W7 64bit
 - Browser firefox
 - Version 115.22.0esr
 - locale: french

**Additional context**
Work fine with v 2.5.8.1
OK with 2.5.9.2 just after "display"->"refresh"
![Image](https://github.com/user-attachments/assets/6a33fb83-a358-4b47-946a-2eb5d21007c7)

**Comment by stephanmahieu** [comment]
I suspect it has something to do with the new version of the 3rd party library DataTables.

It tries to load the french locale but that is not part of the distribution and it should then fallback to english. It still does fallback but apparently no longer silent.

I will try to check the presence of the locale myself (or restrict to the available locales) and force english if the locale does not exist.

**Comment by stephanmahieu** [comment]
Should be fixed in v2.5.11.0 which was just released. Can you confirm?

**Comment by chris05** [comment]
I confirm that I no longer have the problem with version 2.5.11.0.

Thank you

**Comment by q00u** [comment]
At least the Manage History bug is still not displaying correctly (without Refresh) in 3.0.3.0

<img width="1017" height="895" alt="Image" src="https://github.com/user-attachments/assets/f679f5e2-a545-4b39-b479-04ef4925414e" />
